config/routes.rb
Rails.application.routes.draw do
  root to: 'example#hello'
  get 'example/hello'
  get 'example/clipboard'
  get 'example/content_loader'
  get 'example/slideshow'
  get 'uptime', to: 'uptime#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/example_controller.rb
class ExampleController < ApplicationController
  def hello
  end

  def clipboard
  end

  def content_loader
  end

  def slideshow
  end
end

app/controllers/uptime_controller.rb
class UptimeController < ApplicationController
  layout false

  def index
    @now = DateTime.now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/helpers/uptime_helper.rb
module UptimeHelper
end

app/views/example/clipboard.html.erb
<p data-controller="clipboard">
  <input data-target="clipboard.source" class="clipboard-source" type="text" value="https://stimulusjs.org" readonly>
  <button data-action="clipboard#copy" class="clipboard-button">Copy</button>
</p>

<p data-controller="clipboard">
  <input data-target="clipboard.source" class="clipboard-source" type="text" value="https://basecamp.com" readonly>
  <button data-action="clipboard#copy" class="clipboard-button">Copy</button>
</p>

<br>

<p>
  <textarea placeholder="Paste here…"></textarea>
</p>

app/views/example/content_loader.html.erb
<p data-controller="content-loader"
   data-content-loader-url="/uptime"></p>

<p data-controller="content-loader"
   data-content-loader-url="/uptime"
   data-content-loader-refresh-interval="3500"></p>

<p data-controller="content-loader"
   data-content-loader-url="/uptime"
   data-content-loader-refresh-interval="1000"></p>

app/views/example/hello.html.erb
<form data-controller="hello" data-action="hello#greet">
  <input data-target="hello.name" type="text" placeholder="Type your name…" autofocus>
  <input type="submit" value="Greet">
</form>

app/views/example/slideshow.html.erb
<div data-controller="slideshow">
  <button data-action="slideshow#previous">←</button>
  <button data-action="slideshow#next">→</button>

  <div data-target="slideshow.slide" class="slide">🐵</div>
  <div data-target="slideshow.slide" class="slide">🙈</div>
  <div data-target="slideshow.slide" class="slide">🙉</div>
  <div data-target="slideshow.slide" class="slide">🙊</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
    <div class="sidebar">
      <img src="/logo.svg" class="logo" alt="Stimulus logo" width="75" height="75">

      <ul class="nav">
        <li><%= link_to "Hello", example_hello_path %></li>
        <li><%= link_to "Clipboard", example_clipboard_path %></li>
        <li><%= link_to "ContentLoader", example_content_loader_path %></li>
        <li><%= link_to "Slideshow", example_slideshow_path %></li>
      </ul>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/uptime/index.html.erb
<%= @now %>